version: '3'
services:
  openvpn-server:
    image: "kylemanna/openvpn:2.4"
    container_name: openvpn-server
    restart: always
    mem_limit: 2G
    cap_add:
      - NET_ADMIN
    volumes:
      - $PWD/openvpn_data:/etc/openvpn:rw
    networks:
      - tools-net
    ports:
      - "1194:1194/udp"

networks:
  # Custom network for isolation
  tools-net:
    name: tools-net
    driver: bridge
